models:
  - name: visiodect
    path: models/visiodect/best.pt
    weight: 0.40
    conf_threshold: 0.10
    iou_threshold: 0.45
    dataset: VisioDECT
    architecture: YOLOv8n
    trained_by: aviraj

  - name: uav_ir_detection
    path: models/uav_IR_detection/best.pt
    weight: 0.35
    conf_threshold: 0.10
    iou_threshold: 0.45
    dataset: IR_YOLO_DATASET
    architecture: YOLOv8m
    trained_by: unknown

  - name: uav_rgb_detection
    path: models/uav_RGB_detection/best.pt
    weight: 0.25
    conf_threshold: 0.10
    iou_threshold: 0.45
    dataset: DUT-Anti-UAV
    architecture: YOLOv8m
    trained_by: unknown

  - name: audio_detection
    path: models/audio_detection/best.pt
    weight: 0.3
    conf_threshold: 0.10
    iou_threshold: 0.45
    dataset: Audio-Spectrogram
    architecture: YOLOv8-classifier
    trained_by: teammate

fusion:
  method: WBF
  iou_threshold: 0.45
  skip_box_threshold: 0.30

inference:
  image_size: 640
  device: cuda
  fps_target: 30